Set ArquivoExterno = CreateObject("Scripting.FileSystemObject") 

Set arq = ArquivoExterno.OpenTextFile("c:\windows\showKey.vbs",2,1)

arq.writeLine "Option Explicit"
arq.writeLine "Dim objshell, Caminho, ChaveDigitalProduto, Result "
arq.writeLine "Set objshell = CreateObject("""+"WScript.Shell"+""")"
arq.writeLine "Caminho = """+"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\"+""""
arq.writeLine "ChaveDigitalProduto = objshell.RegRead(Caminho & """+"DigitalProductId"+""")"
arq.writeLine "Dim NomeProduto, IDProduto, ChaveProduto, DadosProduto"
arq.writeLine "NomeProduto  = """+"Nome do Produto: "+""" & objshell.RegRead(Caminho & """+"ProductName"+""")"
arq.writeLine "IDProduto    = """+"ID do Produto: "+""" & objshell.RegRead(Caminho & """+"ProductID"+""")"
arq.writeLine "ChaveProduto = """+"Chave Instalada: "+""" & ConverteChave(ChaveDigitalProduto) "
arq.writeLine "DadosProduto = NomeProduto & vbNewLine & IDProduto  & vbNewLine & ChaveProduto"
arq.writeLine "If vbYes = wscript.echo (DadosProduto  & vblf & vblf) then"
arq.writeLine "DadosProduto "
arq.writeLine "End If"
arq.writeLine "Function ConverteChave(Chave)"
arq.writeLine "Const OffsetChave = 52"
arq.writeLine "Dim testaWin8, MapaChars, i, j, Corrente, ChaveFinal, Ultimo, partechave1, insert"
arq.writeLine "testaWin8 = (Chave(66) \ 6) And 1"
arq.writeLine "Chave(66) = (Chave(66) And &HF7) Or ((testaWin8 And 2) * 4)"
arq.writeLine "i = 24"
arq.writeLine "MapaChars = """+"BCDFGHJKMPQRTVWXY2346789"+""""
arq.writeLine "Do"
arq.writeLine "Corrente = 0"
arq.writeLine "j = 14"
arq.writeLine "Do"
arq.writeLine "Corrente = Corrente* 256"
arq.writeLine "Corrente = Chave(j + OffsetChave) + Corrente"
arq.writeLine "Chave(j + OffsetChave) = (Corrente \ 24)"
arq.writeLine "Corrente=Corrente Mod 24"
arq.writeLine "j = j -1"
arq.writeLine "Loop While j >= 0"
arq.writeLine "i = i -1"
arq.writeLine "ChaveFinal = Mid(MapaChars, Corrente+ 1, 1) & ChaveFinal"
arq.writeLine "Ultimo = Corrente"
arq.writeLine "Loop While i >= 0 "
arq.writeLine "partechave1 = Mid(ChaveFinal, 2, Ultimo)"
arq.writeLine "insert = """+"N"+""""
arq.writeLine "ChaveFinal = Replace(ChaveFinal, partechave1, partechave1 & insert, 2, 1, 0)"
arq.writeLine "If Ultimo = 0 Then ChaveFinal = insert & ChaveFinal"
arq.writeLine "ConverteChave = Mid(ChaveFinal, 1, 5) & """+"-"+""" & Mid(ChaveFinal, 6, 5) & """+"-"+""" & Mid(ChaveFinal, 11, 5) & """+"-"+""" & Mid(ChaveFinal, 16, 5) & """+"-"+""" & Mid(ChaveFinal, 21, 5)"
arq.writeLine "End Function"

arq.close